{{- if .Values.aircrewTLSSecret | empty | not }}
{{- with .Values.aircrewTLSSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jet-aircrew-helm-chart.fullname" $ }}-tls-secret
  labels:
    {{ include "jet-aircrew-helm-chart.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "Please provide `certificate` for aircrewTLSSecret" .certificate }}
  tls.key: {{ required "Please provide `key` for aircrewTLSSecret" .key }}
{{- end }}
{{- end }}
